### ISSUE TITLE
Proposition d'amélioration des couleurs

### ISSUE THREAD

**Issue by quark67** [cpierquet/trivialpursuit#1]
Pour des couleurs plus fidèles aux couleurs officielles (voir ce plateau de jeu : https://en.wikipedia.org/wiki/Trivial_Pursuit#/media/File:Trivial_Pursuit.jpg), à moins que vous ne teniez pour des raisons de droits à rester éloigné des couleurs officielles, je vous propose le changement suivant :

```latex
\definecolor{TPorange}{cmyk}{0,0.6,1,0}
\definecolor{TPblue}{cmyk}{0.7,0,0,0}
\definecolor{TPbrown}{cmyk}{0.3,0.5,0.7,0}
\definecolor{TPgreen}{cmyk}{0.7,0,0.8,0}
\definecolor{TPpink}{cmyk}{0,0.6,0,0}
```

puis de remplacer : 

```latex
ListeCouleurs={yellow,orange,blue,brown,green,pink},%
```

par : 

```latex
ListeCouleurs={yellow,TPorange,TPblue,TPbrown,TPgreen,TPpink},%
```

(la couleur jaune est conservée, donc pas de changement pour elle).

J'ai employé le préfixe TP pour des raisons évidentes, à changer si besoin.

J'ai choisi le modèle de couleur CMYK pour définir les couleurs dans xcolor, afin de rester le plus proche possible des couleurs imprimables, si certaines personnes souhaitaient imprimer des plateaux de jeu.

Voici les couleurs (j'ai employé la palette des couleurs de macOS et sa pipette, et j'ai arrondi au dixième la valeur de chaque couleur primaire du modèle CMYK — cyan, magenta, jaune, noir) : 

<img width="739" alt="image" src="https://github.com/cpierquet/trivialpursuit/assets/9338576/fad1af2c-0d9a-4245-833f-df527931e3af">

Et cela donne : 

<img width="485" alt="image" src="https://github.com/cpierquet/trivialpursuit/assets/9338576/f101cb1c-5bc3-45ee-9f59-d8a88cec1913">

Si le orange paraît un peu trop sombre, on peut envisager le code alternatif : `\definecolor{TPorange}{cmyk}{0,0.5,1,0}`.

À gauche, la couleur que j'ai défini en premier lieu pour une meilleure saturation, à droite la teinte alternative : 
<img width="164" alt="image" src="https://github.com/cpierquet/trivialpursuit/assets/9338576/92c432a1-4bf1-4eed-9be8-feaad250275f">

N'ayant pas de plateau sous les yeux ni d'imprimante couleur, je ne sais pas ce qui est le mieux.

**Comment by quark67** [comment]
C'est effectivement sans doute mieux de ne pas mettre par défaut les couleurs officielles, et de présenter la documentation avec une palette de couleurs alternative.

La palette suivante : 

```latex
\definecolor{TPyellow}{cmyk}{0,0,0.75,0}
\definecolor{TPorange}{cmyk}{0,0.25,0.95,0}
\definecolor{TPblue}{cmyk}{0.65,0.1,0.1,0}
\definecolor{TPbrown}{cmyk}{0.15,0.3,0.85,0}
\definecolor{TPgreen}{cmyk}{0.3,0,0.95,0}
\definecolor{TPpink}{cmyk}{0.0,0.65,0.4,0}
```

produit : 

<img width="452" alt="image" src="https://github.com/cpierquet/trivialpursuit/assets/9338576/3a864d7e-ba50-4315-99ad-8cfbbce6994a">

C'est probablement assez éloigné des couleurs officielles tout en ayant une certaine harmonie.

Indiquer des couleurs proches des couleurs officielles uniquement sous la forme d'une suggestion de code avec les valeurs fournies dans le premier message (en remplaçant le préfixe TP ?) pourrait être une solution pour les personnes qui souhaitent avoir quelque chose de très réaliste.

**Comment by cpierquet** [comment]
Je vais sans doute opter pour la solution "proposer des couleurs presque officielles et le mentionner dans la doc". Je m'en occupe après avoir géré un petit problème de licence sur un autre package...
